language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t awshalifax/client:test -f ./client/Dockerfile.dev ./client

scripts:
  - docker run -e CI=true awshalifax/client:test npm run test

after_success:
  - docker build -t awshalifax/client:latest ./client
  - docker build -t awshalifax/nginx:latest ./nginx
  - docker build -t awshalifax/server:latest ./server
  - docker build -t awshalifax/worker:latest ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push awshalifax/client:latest
  - docker push awshalifax/nginx:latest
  - docker push awshalifax/server:latest
  - docker push awshalifax/worker:latest
